services:
  pagamentos:
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./aluraFood/:/app
      - /app/target
    networks:
      - internalNetwork
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      - spring.datasource.url=jdbc:mysql://db-pagamentos:3306/aluraPag?serverTimezone=UTC&createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.show-sql=true
      - eureka.client.serviceUrl.defaultZone=http://serviceDiscovery:8081/eureka
      - server.port=0
    depends_on:
      - db-pagamentos

  db-pagamentos:
    image: mysql:8.0
    networks:
      - internalNetwork
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aluraPag
    volumes:
      - db-data:/var/lib/mysql

  pedidos:
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./aluraPedidos-ms/:/app
      - /app/target
    networks:
      - internalNetwork
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      - spring.datasource.url=jdbc:mysql://db-pagamentos:3306/alurafood-pedidos?serverTimezone=UTC&createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.show-sql=true
      - eureka.client.serviceUrl.defaultZone=http://serviceDiscovery:8081/eureka
      - server.port=0
    depends_on:
      - db-pedidos

  db-pedidos:
    image: mysql:8.0
    networks:
      - internalNetwork
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alurafood-pedidos
    volumes:
      - db-data2:/var/lib/mysql
  

  serviceDiscovery:
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./serviceDiscoveryFood/:/app
      - /app/target
    networks:
      - internalNetwork
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      - server.port=8081
      - eureka.client.serviceUrl.defaultZone=http://serviceDiscovery:8081/eureka
  
  gateway:
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./gateway/:/app
      - /app/target
    networks:
      - internalNetwork
    ports:
      - "8080:8082"
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      - server.port=8082
      - eureka.client.serviceUrl.defaultZone=http://serviceDiscovery:8081/eureka

volumes:
  db-data:
  db-data2:
networks:
  bridgeNetwork:
    driver: bridge
  internalNetwork:
    driver: bridge
  